.default_json_check: &default_json_check
  up:
    connect_timeout: 1
    read_timeout: 5
    status_code: 200
    json:
      path: ".status"
      value: "UP"
    response:
      status_code: 200
      content_type: application/json
      body: '{ "status": "UP", "description": "Everything is alright" }'
  down:
    response:
      status_code: 503
      content_type: application/json
      body: '{ "status": "DOWN", "description": "The service is unavailable" }'
checks:
- name: test-timeout-1s
  endpoint: http://httpstat.us/200?sleep=1000
  <<: *default_json_check
- name: test-timeout-2s
  endpoint: http://httpstat.us/200?sleep=2000
  <<: *default_json_check
- name: test-timeout-3s
  endpoint: http://httpstat.us/200?sleep=3000
  <<: *default_json_check
- name: test-timeout-4s
  endpoint: http://httpstat.us/200?sleep=4000
  <<: *default_json_check
- name: test-timeout-5s
  endpoint: http://httpstat.us/200?sleep=5000
  <<: *default_json_check
- name: test-timeout-10s
  endpoint: http://httpstat.us/200?sleep=10000
  <<: *default_json_check
- name: test-timeout-20s
  endpoint: http://httpstat.us/200?sleep=20000
  <<: *default_json_check
